-- Part 2: sepet yogunlasma kontrolleri icin kalici sektor ve bolge bilgisi.

BEGIN;

ALTER TABLE assets
    ADD COLUMN IF NOT EXISTS sector VARCHAR(40),
    ADD COLUMN IF NOT EXISTS region VARCHAR(16);

UPDATE assets SET
    sector = CASE symbol
        WHEN 'THYAO' THEN 'TRANSPORTATION'
        WHEN 'GARAN' THEN 'FINANCIALS'
        WHEN 'TCELL' THEN 'COMMUNICATION'
        WHEN 'SASA' THEN 'MATERIALS'
        WHEN 'ASELS' THEN 'INDUSTRIALS'
        WHEN 'EREGL' THEN 'MATERIALS'
        WHEN 'BIMAS' THEN 'CONSUMER_STAPLES'
        WHEN 'TUPRS' THEN 'ENERGY'
        WHEN 'KCHOL' THEN 'DIVERSIFIED'
        WHEN 'SISE' THEN 'MATERIALS'
        WHEN 'AKCNS' THEN 'MATERIALS'
        WHEN 'TOASO' THEN 'CONSUMER_DISCRETIONARY'
        WHEN 'KONTR' THEN 'INDUSTRIALS'
        WHEN 'AAPL' THEN 'TECHNOLOGY'
        WHEN 'TSLA' THEN 'CONSUMER_DISCRETIONARY'
        WHEN 'NVDA' THEN 'TECHNOLOGY'
        WHEN 'MSFT' THEN 'TECHNOLOGY'
        WHEN 'AMZN' THEN 'CONSUMER_DISCRETIONARY'
        WHEN 'GOOG' THEN 'COMMUNICATION'
        WHEN 'META' THEN 'COMMUNICATION'
        WHEN 'BRK-B' THEN 'FINANCIALS'
        WHEN 'JPM' THEN 'FINANCIALS'
        WHEN 'LLY' THEN 'HEALTHCARE'
        WHEN 'INTC' THEN 'TECHNOLOGY'
        WHEN 'WMT' THEN 'CONSUMER_STAPLES'
        WHEN 'KO' THEN 'CONSUMER_STAPLES'
        WHEN 'T' THEN 'COMMUNICATION'
        WHEN 'GRAM_ALTIN' THEN 'PRECIOUS_METALS'
        WHEN 'GUMUS' THEN 'PRECIOUS_METALS'
        WHEN 'BRENT' THEN 'ENERGY'
        WHEN 'BAKIR' THEN 'INDUSTRIAL_METALS'
        WHEN 'MISIR' THEN 'AGRICULTURE'
        WHEN 'BTC' THEN 'DIGITAL_ASSETS'
        WHEN 'ETH' THEN 'DIGITAL_ASSETS'
        WHEN 'SOL' THEN 'DIGITAL_ASSETS'
        WHEN 'USDT' THEN 'DIGITAL_ASSETS'
        WHEN 'SPY' THEN 'DIVERSIFIED'
        WHEN 'QQQ' THEN 'TECHNOLOGY'
        WHEN 'VTI' THEN 'DIVERSIFIED'
        WHEN 'USD/TRY' THEN 'CURRENCY'
        WHEN 'EUR/TRY' THEN 'CURRENCY'
        WHEN 'US10Y' THEN 'FIXED_INCOME'
        ELSE COALESCE(sector, 'OTHER')
    END,
    region = CASE
        WHEN symbol IN (
            'THYAO','GARAN','TCELL','SASA','ASELS','EREGL','BIMAS',
            'TUPRS','KCHOL','SISE','AKCNS','TOASO','KONTR'
        ) THEN 'TR'
        WHEN symbol IN (
            'AAPL','TSLA','NVDA','MSFT','AMZN','GOOG','META','BRK-B','JPM',
            'LLY','INTC','WMT','KO','T','SPY','QQQ','VTI','US10Y'
        ) THEN 'US'
        ELSE 'GLOBAL'
    END;

ALTER TABLE assets
    ALTER COLUMN sector SET NOT NULL,
    ALTER COLUMN region SET NOT NULL;

COMMIT;
